services:
  backend:
    build:
      context: backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@ep-round-wave-a4ppyklf-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&options=endpoint%3Dep-round-wave-a4ppyklf

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

# Remove this db section if you're using Neon and not local postgres
# db:
#   image: postgres:latest
#   environment:
#     POSTGRES_USER: craivings_user
#     POSTGRES_PASSWORD: password
#     POSTGRES_DB: db_craivings
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   ports:
#     - "5432:5432"

volumes:
  postgres_data:
    driver: local
