-- Export data from the restaurant table with tsvector cast to text
\copy (SELECT id, name, address, city, state, postal_code, latitude, longitude, stars, review_count, is_open FROM restaurant) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, category FROM restaurant_categories) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_categories.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, day_of_week, open_time, close_time FROM restaurant_hours) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_hours.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, by_appointment_only, accept_credit_cards, restaurant_price_range, coat_check, take_out, delivery, caters, wifi, wheelchair, happy_hour, outdoor_seating, tv, reservation, dogs_allowed, alcohol, good_for_kids, restaurants_attire, restaurant_table_service, drive_thru, noise_level, accepts_bitcoin, smoking, good_for_dancing, accepts_insurance, best_nights, byob, corkage, byob_corkage, open_24_hours, restaurant_counter_services, ages_allowed FROM restaurant_attributes) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_attributes.csv'
\copy (SELECT business_id, day_of_week FROM restaurant_best_nights) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_best_nights.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, music FROM restaurant_music) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_music.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, dietary FROM restaurant_dietary) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_dietary.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, parking_type FROM restaurant_parking) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_parking.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, vibe FROM restaurant_ambience) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_ambience.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, occasion FROM restaurant_good_for_meal) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_good_for_meal.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');
\copy (SELECT business_id, attribute_key, attribute_value FROM restaurant_dynamic_attributes) TO '/Users/rheekang/docker_projects/crAIvings/code/data/clean/restaurant_dynamic_attributes.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');

